import * as fs from 'node:fs';
import * as path from 'node:path';

const ROOT = path.resolve(__dirname, '../..');
const SANDCASTLE = path.join(ROOT, '.sandcastle');

function read(file: string) {
  return fs.readFileSync(path.join(SANDCASTLE, file), 'utf8');
}

describe('sandcastle merge-prompt PR body enrichment', () => {
  const content = read('agent-docs/merge-prompt.md');

  it('fetches the issue body via gh issue view --json body', () => {
    expect(content).toMatch(/gh issue view.*--json body/);
  });

  it('instructs the merger to extract the Acceptance criteria section', () => {
    expect(content).toMatch(/### Acceptance criteria/);
  });

  it('instructs the merger to include a Files changed section', () => {
    expect(content).toMatch(/[Ff]iles changed/);
  });

  it('derives files-changed from git diff --stat', () => {
    expect(content).toMatch(/git diff.*--stat/);
  });

  it('instructs the merger to copy the Out of scope section', () => {
    expect(content).toMatch(/### Out of scope/);
  });

  it('includes [x] and [ ] checkbox inference instructions', () => {
    expect(content).toMatch(/\[x\]/);
    expect(content).toMatch(/\[ \]/);
  });

  it('preserves the 🤖 Generated by Sandcastle footer in the template', () => {
    expect(content).toMatch(/Generated by Sandcastle/);
  });

  it('instructs graceful omission when no Acceptance criteria section exists', () => {
    expect(content).toMatch(
      /graceful|omit|fall.?back|no.*acceptance.?criteria|if.*not.*found|absent|missing/i,
    );
  });

  it('PR body template contains the five required sections', () => {
    expect(content).toMatch(/### Acceptance criteria/);
    expect(content).toMatch(/### Files changed/);
    expect(content).toMatch(/### Out of scope/);
    expect(content).toMatch(/Closes #/);
    expect(content).toMatch(/Generated by Sandcastle/);
  });
});
